### ISSUE TITLE
Automatic refresh fails if you use a # for numbered list in your adoc file.

### ISSUE THREAD

**Issue by escay** [asciidoctor/atom-asciidoc-preview#172] opened 2016-06-06 11:48 UTC
## Description

Automatic refresh fails if you start a numbered list in your adoc file with a #, instead of a dot (.)
Using # is quite common in other markup languages. I suspect there will be more victims than just me that accidentally use it.

It is quite annoying if you accidentally use a # for a numbered list and you see a few minutes later that automatic refresh is no longer working and there is no way to get it to work again. Luckily I was able to pinpoint the issue back to the #

I use Atom 1.7.4 on Windows 10, 64 bit
Packages installed:
- asciidoc-preview v. 2.2.5
- language-asciidoc v. 1.4.9

If this issue is not a asciidoc-preview bug but a language-asciidoc bug I hope that the asciidoc-preview can be improved so that the preview shows some kind of error message to give the end user a hint.

## Syntax example failure

```adoc
= Test
:doctype: book

== Hello

Example 2 steps:

# step 1
# step 2

End of example
```

Once the # is used as a list the preview rendering starts to fail, without a visible error. The entire tab seems to be frozen. Closing the preview and reopening again does not help, the loading image is now shown and keeps showing. Uninstall and reinstall of plugins does not help.

## Syntax example success

```adoc
= Test
:doctype: book

== Hello

Example 2 steps:

. step 1
. step 2

End of example
```

If the # in the numbered list is replaced with the . the preview window starts to work again.

Perhaps this issue is related to #159?
When I enable the developer tools and I store the list using a # I see the following exception and the preview no longer updates.

```
EPERM: operation not permitted, write Error: EPERM: operation not permitted, write
    at Error (native)
    at Object.fs.writeSync (fs.js:706:20)
    at SyncWriteStream.write (fs.js:2059:6)
    at $IO.write_proc (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\node_modules\opal-npm-wrapper\index.js:18516:89)
    at $IO.$write (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\node_modules\opal-npm-wrapper\index.js:18413:12)
    at $IO.$puts (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\node_modules\opal-npm-wrapper\index.js:18467:16)
    at SingletonClass_alloc.$warn (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\node_modules\opal-npm-wrapper\index.js:4255:43)
    at SingletonClass_alloc.$next_section (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\npm\asciidoctor-core.min.js:384:412)
    at SingletonClass_alloc.$parse (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\npm\asciidoctor-core.min.js:371:247)
    at f.$parse (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\npm\asciidoctor-core.min.js:323:183)
    at module_constructor.$load (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\npm\asciidoctor-core.min.js:642:89)
    at module_constructor.<anonymous> (C:\Users\mmorrien\.atom\packages\asciidoc-preview\node_modules\asciidoctor.js\dist\npm\asciidoctor-core.min.js:645:369)
    at Object.module.exports (file:///C:/Users/mmorrien/.atom/packages/asciidoc-preview/lib/worker.coffee:30:22)
    at process.<anonymous> (C:\Users\mmorrien\AppData\Local\atom\app-1.7.4\resources\app.asar\src\task-bootstrap.js:84:10)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:686:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

**Comment by ldez** [comment] 2016-06-06 12:11
`#` at the start of a line define a title (H1), perhaps this use of `#` come from the old AcsiiDoc Python.

In a AsciiDoctor, ordered list is defined by `.`, `1.`, `I)`, etc but not with `#`

See the documentation: http://asciidoctor.org/docs/user-manual/#ordered-lists

Otherwise, your bug come from asciidoctor.js on Win10, see #159

**Comment by escay** [comment] 2016-06-06 14:17
Thank you. I known I should not have used # for an ordered list, but refreshing should still work if incorrect asciidoc is written, or an error should be displayed in the preview window to inform the user that refreshing was impossible due to incorrect asciidoc. I will test the scenario again once #159 is fixed.

**Comment by ldez** [comment] 2016-06-06 14:29
I'm agree with you.
For now Asciidoctor.js  doesn't provide a system for report errors and warnings see https://github.com/asciidoctor/asciidoctor.js/issues/187

**Comment by Mogztter** [comment] 2016-06-06 14:52
I think, for now, we should surround the `convert` method with `try/catch` and show the error message: https://github.com/asciidoctor/asciidoctor-chrome-extension/blob/master/app/js/renderer.js#L62

**Comment by ldez** [comment] 2016-06-06 17:53
Duplicate of #159

**Comment by ldez** [comment] 2016-06-06 18:04
I can do that but the error will be very hard to understand for the end user.

We must be able to capture `stderr`, `stdout`.

**Comment by ldez** [comment] 2016-06-06 18:11
Maybe use `opalParam` to create a wrapper around Opal and hack the output?

**Comment by ldez** [comment] 2016-06-07 19:30
close in favor of #159 and the workaround in #174

**Closed by ldez** 2016-06-07 19:30 UTC
Labels: asciidoctor.js, bug, duplicate, preview, windows

**Comment by mojavelinux** [comment] 2016-06-08 00:37
> # at the start of a line define a title (H1), perhaps this use of # come from the old AsciiDoc Python.

This actually comes from compatibility mode with Markdown.

**Comment by ldez** [comment] 2016-06-08 05:37
I misspoke:
> perhaps this use of `#`  **as ordered list**  come from the old AsciiDoc Python.

**Comment by mojavelinux** [comment] 2016-06-08 05:58
Ah, I see what you were saying. But nope, `#` was never supported in AsciiDoc for lists. However, it does appear in many other lightweight markup languages.

**Comment by escay** [comment] 2016-06-08 06:19
I confirm the workaround of #174 works in plugin version 2.3.1 on Windows 10, 64 bit, I get a nice error message. This is a very nice improvement!
Note: after upgrading the plugin I had to close preview tab and restart Atom to ensure the 2.3.1 version of the plugin was loaded.
