### ISSUE TITLE
Specifying custom css file

### ISSUE THREAD

**Issue by refaelsh** [asciidoctor/atom-asciidoc-preview#314] opened 2020-12-31 19:00 UTC
Hi,

The README file says : "If you want to customize the apparance of the preview, you can specify your own stylesheet in the settings".

So I added `stylesheet=mystylesheet.css` in package settings - in the `Default Attributes` field, but it doesn't work.
I still see the default stylesheet in the preview.

Thanks.

**Comment by ldez** [comment] 2020-12-31 20:33
duplicate of #313

**Closed by ldez** 2020-12-31 20:33 UTC
