### ISSUE TITLE
Change theme for preview pane

### ISSUE THREAD

**Issue by tuxGurl** [asciidoctor/atom-asciidoc-preview#256] opened 2017-12-18 18:21 UTC
## Description
How do I change the theme used in the preview pane? 

I have a custom yml theme that I use when exporting to PDF. I'd like to modify the theme used by the preview pane to be similar to the custom PDF theme so that I can preview roughly what the output would be.

- Atom version: 1.23.1 x64
- OS: Windows
- `asciidoc-preview` version: 2.10.3
- `language-asciidoc` version: 1.11.0

**Comment by ldez** [comment] 2017-12-18 18:58
Thanks for your interest 👍 

Currently it's not possible to change the theme of the preview.

Duplicate of https://github.com/asciidoctor/atom-asciidoc-preview/issues/39

**Closed by ldez** 2017-12-18 18:58 UTC
Labels: duplicate
