### ISSUE TITLE
Suggestion popup for attributes pops up everywhere in line after an attribute

### ISSUE THREAD

**Issue by ygra** [asciidoctor/atom-asciidoc-preview#130] opened 2016-04-26 13:17 UTC
If I have a line like this:

    {someattribute} foo

then trying to write text at the end of that line (or anywhere after the attribute, for that matter), will pop up the suggestions on nearly every keystroke.

**Comment by mojavelinux** [comment] 2016-05-10 06:56
I've learned that the autocomplete-plus package has numerous configuration settings to tune when the suggestions popup. In fact, you can disable the auto-popup outright so that they only appear when you press the trigger keyboard shortcut, Ctrl+Space. See the related discussion starting at the comment https://github.com/asciidoctor/atom-language-asciidoc/pull/98#issuecomment-217863665.

**Comment by ygra** [comment] 2016-05-10 12:12
Ok, that showed me a way to avoid the largest annoyance with that, but fundamentally I believe suggestions to complete an attribute name should really only appear within `{}`, not on the complete line after an attribute. (This wasn't about snippets, but rather the auto-completion list of document attributes)

**Comment by mojavelinux** [comment] 2016-05-10 21:12
That's a very good point. We need to tune the following two settings in *lib/attributes-provider.coffee*:

```
  selector: ".source.asciidoc"
  disableForSelector: ".source.asciidoc .comment.block.asciidoc"
```

We should only enable it for the following selector:

```
  selector: ".markup.substitution.attribute-reference.asciidoc"
```

That way, we know we're inside the boundaries of an attribute reference.

cc: @nicorikken @ldez

**Comment by mojavelinux** [comment] 2016-05-10 21:20
@nicorikken @ldez I think the naming for an attribute reference should be as follows:

```
.meta.attribute-reference.asciidoc
  support.function.attribute-directive.asciidoc
  variable.other.attribute-name.asciidoc
```

Where the "meta" is applied to the whole reference, the "support" is applied to the "set:" (if present), and the "variable" is applied just to the name.

I'm also open to shortnames:

* attrref
* attrfn
* attrname

wdyt?

**Comment by ldez** [comment] 2016-05-10 21:34
It seems right.
I prefer long names. :wink:

**Comment by mojavelinux** [comment] 2016-05-10 22:04
> I prefer long names. 

:+1: 

Makes me wonder if we should switch to "attribute-list" instead of "attrlist". But that's a separate discussion.

**Comment by nicorikken** [comment] 2016-05-21 11:20
Side track: shouldn't the autocompletion moved over to the language repo, as this relates to the source code rather than the preview? By working on the naming we now create hard dependencies between both packages, possibly breaking functionality when naming changes in either of the repo's. If others agree I'd rather have such a migration sooner than later, to enable a migration path (current version available in both packages for a while), and to reduce additional inter-project coordination.

**Comment by ldez** [comment] 2016-05-21 11:29
I agree and opened issues #139 and https://github.com/asciidoctor/atom-language-asciidoc/issues/133.

To do that, we must reactivate development activities on `asciidoc-preview` to reduce cross-feature problem.

@mojavelinux can you help us ?

**Comment by nicorikken** [comment] 2016-05-21 11:49
As I commented on #39 currently I cannot get into development of this package as a result of the `atom-space-pen-views` dependency. Maybe I'm doing something wrong. This however similar to the `markdown-preview` package, which seems odd.

**Comment by ldez** [comment] 2016-05-21 11:52
have you do `apm install` ?

**Comment by nicorikken** [comment] 2016-05-21 11:57
I can get the normal package to work (although I've used the graphical install rather than the cli install). But when opening up for development (checked out the repo and doing `apm link -d`) I get the `atom-space-pen-views` error. How about you?

**Comment by ldez** [comment] 2016-05-21 11:59
I used the graphical install.

```shell
git clone git@github.com:asciidoctor/atom-asciidoc-preview.git
cd atom-asciidoc-preview
apm install
apm link -d
```

**Comment by mojavelinux** [comment] 2016-05-21 20:47
@ldez I'm definitely ready to help. @Mogztter has been working through a lot of issues lately as well. We're back in business!

**Comment by mojavelinux** [comment] 2016-05-21 20:48
@ldez @nicorikken I think we need a contributing guide like the excellent one in the language package.

**Comment by mojavelinux** [comment] 2016-05-21 20:52
I can confirm that by following the instructions by @ldez, I am able to load the package in dev. I'm using Atom 1.7.1.

**Comment by nicorikken** [comment] 2016-05-22 07:28
Thanks, I didn't execute the `apm install`. Now I can get going 👍

**Comment by ldez** [comment] 2016-05-24 17:08
Since 1.0.0, the autocompletions have been migrated to a new package: [autocomplete-asciidoc](https://atom.io/packages/autocomplete-asciidoc)

This issue is fixed in the new package.

**Closed by ldez** 2016-05-24 17:08 UTC
Labels: autocomplete, bug
