### ISSUE TITLE
Preview Style And Font

### ISSUE THREAD

**Issue by magnus-lutz** [asciidoctor/atom-asciidoc-preview#204] opened 2016-12-01 15:39 UTC
Is there a standard theme being used in the plugin or the style and font definitions somewhat external, so that I can include them in my own project, too?
Because I really like the style seen in the preview, while if i compile it on my own the result asciidoc produces looks quite unspectacular

**Comment by ldez** [comment] 2016-12-01 16:26
Duplicate of #39

**Closed by ldez** 2016-12-01 16:26 UTC
Labels: duplicate
