### ISSUE TITLE
Installing on Windows 7 Fails with atom-space-pen-views module error.

### ISSUE THREAD

**Issue by jaredmorgs** [asciidoctor/atom-asciidoc-preview#112] opened 2015-11-18 04:56 UTC
[Enter steps to reproduce below:]
 
1. Install asciidoc-preview through atom.
2. Version 0.6.0 fails so go and download 0.5.1 and manually install.
3. Drop folder into .atom directory.
4. Restart atom.
5. Get the following stack trace warning.
 
**Atom Version**: 1.2.1
**System**: Microsoft Windows 7 Professional
**Thrown From**: [atom-asciidoc-preview-0.5.1](https://github.com/asciidoctor/atom-asciidoc-preview) package, vundefined
 
 
### Stack Trace
 
Failed to load the asciidoc-preview package
 
```
At Cannot find module 'atom-space-pen-views'
 
Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (C:\Users\renata.casamento\AppData\Local\atom\app-1.2.1\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (file:///C:/Users/renata.casamento/.atom/packages/atom-asciidoc-preview-0.5.1/lib/asciidoc-preview-view.coffee:3:24)
    at Object.<anonymous> (file:///C:/Users/renata.casamento/.atom/packages/atom-asciidoc-preview-0.5.1/lib/asciidoc-preview-view.coffee:1:1)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .coffee] (C:\Users\renata.casamento\AppData\Local\atom\app-1.2.1\resources\app.asar\src\compile-cache.js:190:21)
    at Module.load (module.js:355:32)
```
 
### Commands
 
```
```
 
### Config
 
```json
{
  "core": {}
}
```
 
### Installed Packages
 
```coffee
# User
No installed packages
 
# Dev
No dev packages

**Comment by nicorikken** [comment] 2016-05-21 10:00
I can confirm this. Seems not to be OS dependent. The atom-space-pen-views package was previously in core, but has now been removed from core, and is to be deprecated. I lack knowledge on whether or not the dependency can be remove or replaced for more upstream packages. https://github.com/atom/atom-space-pen-views

**Comment by Mogztter** [comment] 2016-05-21 21:17
Reference: http://flight-manual.atom.io/upgrading-to-1-0-apis/sections/upgrading-your-package/

Maybe version 0.5.1 is incompatible with Atom 1+ ? (although `atom-space-pen-views` is defined as a dependency in [package.json](https://github.com/asciidoctor/atom-asciidoc-preview/blob/v0.5.1/package.json#L24))

> Version 0.6.0 fails

@jaredmorgs @nicorikken Could you explain why version 0.6.0 fails ?

**Comment by mojavelinux** [comment] 2016-05-21 21:23
I just tested with Atom 1.7.3 and it works. It may be because `npm install` was used instead of `apm install`.

**Comment by Mogztter** [comment] 2016-05-21 21:34
Same here, I've just installed Atom 1.7.3 on Windows 10 with Asciidoc Preview 0.6.0. Maybe we should update the engines field and fix dependency version?

```json
{
  "engines": {
    "atom": ">=0.174.0 <2.0.0"
  }
}
```
```json
{
  "dependencies": {
    "atom-space-pen-views": "2.2.0"
  }
}
```
http://flight-manual.atom.io/upgrading-to-1-0-apis/sections/upgrading-your-package/

**Comment by mojavelinux** [comment] 2016-05-21 21:40
Seems reasonable to me.

**Comment by ldez** [comment] 2016-05-24 17:12
Can you retry with the 1.0.0 ?

**Comment by ldez** [comment] 2016-05-25 20:16
fixed in 1.0.0.

**Closed by ldez** 2016-05-25 20:16 UTC
Labels: bug, more-information-needed

**Comment by gparent** [comment] 2016-05-27 18:45
How was this fixed? I get the same error with Atom 1.7.4 and asciidoc-preview-1.0.4

**Comment by ldez** [comment] 2016-05-27 21:06
@gparent you use this in dev context?

**Comment by ldez** [comment] 2016-05-27 21:34
@gparent Some questions:
- it's a package update? if yes do: `apm uninstall asciidoc-preview` and `apm install asciidoc-preview`
- developer mode with a fork? if yes, go to your local fork directory and do: `apm install`
- other cases? Open a new issue and explains your context.
    - OS?
    - package list: `apm list`

**Comment by gparent** [comment] 2016-05-27 22:28
Using apm install fails to work because I apparently do not have the C++ compiler tools installed.

So I tried using the version on the Releases tab, and extracted it to my .packages directory. I then get stack traces that are very similar to the issue here, to the point where I was hesitating to open a new issue since I seemed to be hitting the same bug (And I am also on Windows 7).

As far as I'm aware I'm not using dev mode. If it's a thing to develop Atom features, I sure hope I'm not using it. There is no icon at the bottom left that says "This window is in Dev Mode", like the one I get when I purposely try to put Atom into that mode through the menu.

On my work computer, I was using Atom 1.7.1 with asciidoc-preview 0.5.1 and was getting this error. Reinstalling 1.7.4 from scratch did not help. I tried Atom 1.8.0beta4 as well. By scratch I mean deleting the ~/.atom and ~/AppData/Local/atom directories then running AtomSetup.exe, shutting down the app, then adding asciidoctor-preview and atom-space-pen-views to ~/.atom/packages and starting the application a second time. Both show up as installed packages in the community section.

I was pretty confident this was a widespread issue (or that I'm clearly doing something wrong) so I reinstalled it on this computer just for kicks, exact same bug.

I will totally re-open a new issue if you think this is worth it. Right now the linked issue if I click on my stack trace is https://github.com/asciidoctor/atom-asciidoc-preview/issues/91

Windows 7, Atom 1.7.4, asciidoctor-preview 1.0.4, atom-space-pen-views 2.2.0

Packages list:

```
> apm list
Built-in Atom Packages (89)
├── about@1.4.2
├── archive-view@0.61.1
├── atom-dark-syntax@0.27.0
├── atom-dark-ui@0.51.0
├── atom-light-syntax@0.28.0
├── atom-light-ui@0.43.0
├── autocomplete-atom-api@0.10.0
├── autocomplete-css@0.11.0
├── autocomplete-html@0.7.2
├── autocomplete-plus@2.29.1
├── autocomplete-snippets@1.10.0
├── autoflow@0.27.0
├── autosave@0.23.1
├── background-tips@0.26.0
├── base16-tomorrow-dark-theme@1.1.0
├── base16-tomorrow-light-theme@1.1.1
├── bookmarks@0.38.2
├── bracket-matcher@0.81.0
├── command-palette@0.38.0
├── deprecation-cop@0.54.1
├── dev-live-reload@0.47.0
├── encoding-selector@0.21.0
├── exception-reporting@0.37.0
├── find-and-replace@0.199.0
├── fuzzy-finder@1.0.5
├── git-diff@1.0.1
├── go-to-line@0.30.0
├── grammar-selector@0.48.1
├── image-view@0.57.0
├── incompatible-packages@0.25.1
├── keybinding-resolver@0.35.0
├── language-c@0.51.1
├── language-clojure@0.20.0
├── language-coffee-script@0.46.1
├── language-csharp@0.12.0
├── language-css@0.36.0
├── language-gfm@0.85.0
├── language-git@0.12.1
├── language-go@0.42.0
├── language-html@0.44.1
├── language-hyperlink@0.16.0
├── language-java@0.17.0
├── language-javascript@0.110.0
├── language-json@0.17.6
├── language-less@0.29.0
├── language-make@0.21.0
├── language-mustache@0.13.0
├── language-objective-c@0.15.1
├── language-perl@0.32.0
├── language-php@0.37.0
├── language-property-list@0.8.0
├── language-python@0.43.0
├── language-ruby@0.68.3
├── language-ruby-on-rails@0.25.0
├── language-sass@0.46.0
├── language-shellscript@0.21.0
├── language-source@0.9.0
├── language-sql@0.20.0
├── language-text@0.7.1
├── language-todo@0.27.0
├── language-toml@0.18.0
├── language-xml@0.34.4
├── language-yaml@0.25.1
├── line-ending-selector@0.3.1
├── link@0.31.1
├── markdown-preview@0.158.0
├── metrics@0.53.1
├── notifications@0.63.1
├── one-dark-syntax@1.2.0
├── one-dark-ui@1.2.0
├── one-light-syntax@1.2.0
├── one-light-ui@1.2.0
├── open-on-github@1.0.1
├── package-generator@1.0.0
├── settings-view@0.235.1
├── snippets@1.0.1
├── solarized-dark-syntax@1.0.0
├── solarized-light-syntax@1.0.0
├── spell-check@0.67.0
├── status-bar@1.1.2
├── styleguide@0.45.2
├── symbols-view@0.112.0
├── tabs@0.96.0
├── timecop@0.33.1
├── tree-view@0.205.0
├── update-package-dependencies@0.10.0
├── welcome@0.34.0
├── whitespace@0.32.2
└── wrap-guide@0.38.1

Community Packages (2) C:\Users\mycomp\.atom\packages
├── atom-asciidoc-preview-1.0.4@1.0.4
└── atom-space-pen-views-2.2.0@2.2.0

└── (empty)
```
Here's the trace:

```
Error: Cannot find module 'atom-space-pen-views'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/mycomp/.atom/packages/atom-asciidoc-preview-1.0.4/lib/asciidoc-preview-view.coffee:2:24)
    at Object.<anonymous> (file:///C:/Users/mycomp/.atom/packages/atom-asciidoc-preview-1.0.4/lib/asciidoc-preview-view.coffee:1:1)
    at Module._compile (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Object.<anonymous> (file:///C:/Users/mycomp/.atom/packages/atom-asciidoc-preview-1.0.4/lib/main.coffee:2:23)
    at Object.<anonymous> (file:///C:/Users/mycomp/.atom/packages/atom-asciidoc-preview-1.0.4/lib/main.coffee:1:1)
    at Module._compile (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:715:27)
    at C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:117:28
    at Package.module.exports.Package.measure (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:92:15)
    at Package.module.exports.Package.load (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:457:14)
    at C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:402:19
    at Config.module.exports.Config.transact (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\config.js:312:16)
    at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\package-manager.js:397:19)
    at C:\Users\mycomp\AppData\Local\atom\app-1.7.4\resources\app.asar\src\atom-environment.js:743:28
```

**Comment by ldez** [comment] 2016-05-27 22:32
please do `apm uninstall atom-space-pen-views` and `apm uninstall asciidoc-preview` and `apm install asciidoc-preview`

**Comment by ldez** [comment] 2016-05-27 22:33
You must not install `atom-space-pen-views` manually.

**Comment by gparent** [comment] 2016-05-27 22:34
Okay, will do.

**Comment by gparent** [comment] 2016-05-27 22:41
The reason I was installing it manually was to avoid a problem where an error message said the C++ compilation tools were not installed. In doing so, I thought I needed both packages.

However, seeing that this works on my regular computer makes me believe there may be something else at play on my work one. However that issue is no longer with asciidoc-preview but more with apm/npm I think. Thank you for your help.

**Comment by ldez** [comment] 2016-05-27 23:18
@gparent I suggest you to simply install [asciidoc-assistant](https://atom.io/packages/asciidoc-assistant) package.

This package automatically download right packages:
- [language-asciidoc](https://github.com/asciidoctor/atom-language-asciidoc)
- [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview)
- [autocomplete-asciidoc](https://github.com/asciidoctor/atom-autocomplete-asciidoc)
- [asciidoc-image-helper](https://github.com/asciidoctor/atom-asciidoc-image-helper)
