### ISSUE TITLE
Uncaught Error: Syntax error, unrecognized expression: #look here ()

### ISSUE THREAD

**Issue by pschiffe** [asciidoctor/atom-asciidoc-preview#125] opened 2016-03-08 16:16 UTC
1. Put `()` inside of `<< >>`. For example, this works fine: `hello. <<look here>>` but this shows exception: `hello. <<look here ()>>`

**Atom Version**: 1.5.4
**System**: "Fedora release
**Thrown From**: [asciidoc-preview](https://github.com/asciidoctor/atom-asciidoc-preview) package, v0.6.0

### Stack Trace

Uncaught Error: Syntax error, unrecognized expression: #look here ()

```
At /usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:1458

Error: Syntax error, unrecognized expression: #look here ()
    at Function.Sizzle.error (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:1458:8)
    at Sizzle.tokenize (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2075:11)
    at Sizzle.select (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2479:20)
    at Function.Sizzle [as find] (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:855:9)
    at [object Object].jQuery.fn.extend.find (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2695:11)
    at [object Object].jQuery.fn.init (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:2803:38)
    at jQuery (/usr/share/atom/resources/app.asar/node_modules/jquery/dist/jquery.js:76:10)
    at AsciiDocPreviewView.module.exports.AsciiDocPreviewView.enableAnchorScroll (/home/pschiffe/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:175:21)
    at /home/pschiffe/.atom/packages/asciidoc-preview/lib/asciidoc-preview-view.coffee:147:8
    at Task.callback (/home/pschiffe/.atom/packages/asciidoc-preview/lib/renderer.coffee:32:5)
    at /usr/share/atom/resources/app.asar/src/task.js:65:72
    at /usr/share/atom/resources/app.asar/src/task.js:126:25
    at Function.module.exports.Emitter.simpleDispatch (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app.asar/node_modules/event-kit/lib/emitter.js:125:28)
    at ChildProcess.<anonymous> (/usr/share/atom/resources/app.asar/src/task.js:78:34)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
    at Pipe.channel.onread (internal/child_process.js:440:11)
```

### Commands

```
     -2:27.4.0 core:delete (atom-text-editor.editor.is-focused)
  3x -2:27.1.0 core:move-right (atom-text-editor.editor.is-focused)
     -2:26.1.0 core:delete (atom-text-editor.editor.is-focused)
     -2:23.7.0 core:save (atom-text-editor.editor.is-focused)
     -2:07.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -2:07.8.0 core:cancel (atom-text-editor.editor.is-focused)
  3x -2:02.8.0 core:backspace (atom-text-editor.editor.is-focused)
     -2:01.1.0 core:save (atom-text-editor.editor.is-focused)
     -1:10.6.0 tree-view:add-file (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -1:02.6.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:59.9.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:59.9.0 core:cancel (atom-text-editor.editor.is-focused)
     -0:57 asciidoc-preview:toggle (atom-text-editor.editor.is-focused)
  3x -0:45.5.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:14 core:move-right (atom-text-editor.editor.is-focused)
 13x -0:13.7.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  }
}
```

### Installed Packages

```coffee
# User
asciidoc-preview, v0.6.0
language-asciidoc, v0.12.0
save-commands, v0.6.11

# Dev
No dev packages
```

**Comment by Mogztter** [comment] 2016-04-30 13:03
I think this is a duplicate of #123

**Comment by Mogztter** [comment] 2016-04-30 13:04
Related issues: #117 #115 #123 #125

**Closed** 2016-05-16 12:04 UTC
