### ISSUE TITLE
Question : How can we use a different style ?

### ISSUE THREAD

**Issue by cmoulliard** [asciidoctor/atom-asciidoc-preview#196] opened 2016-08-12 11:30 UTC
Asciidoctor provides different styles/themes (https://github.com/asciidoctor/asciidoctor-stylesheet-factory/tree/master/sass).

Is it possible to specify another theme when we generate the HTML (example : foundation, github, ...) ?

**Comment by ldez** [comment] 2016-08-12 17:33
Duplicate of #39

**Closed by ldez** 2016-08-12 17:33 UTC
Labels: duplicate, preview, support
